development:
  adapter: postgresql
  encoding: unicode
  database: test_development
  username:
  password:
  host: localhost
test:
  adapter: postgresql
  encoding: unicode
  database: test_test
  username:
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: test_production
  username:
  password:
