paths:
  jquery: 'jquery-2.10.2'
  underscore: 'lodash.underscore-2.4.1'
  backbone: 'backbone-1.1.0'
  chaplin: 'chaplin-0.12.0'
  bootstrap: 'bootstrap.min'
shim:
  'backbone':
    deps: ['underscore', 'jquery','bootstrap']
    exports: 'Backbone'